jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Build with Maven
      run: ./mvnw  --batch-mode package javadoc:jar site
    - continue-on-error: true
      name: Run integration-test
      run: ./mvnw  --batch-mode integration-test verify
name: ci
on:
  repository_dispatch:
    types: trigger-ga___ci.yaml
